### ISSUE TITLE
The meaning in of splice code

### ISSUE THREAD

**Issue by CrazyHsu** [sunlightwang/FuLeTA#1]
Hello,
I have read your code, but i can't understand the meaning of 'splice code' in [block.pm](https://github.com/sunlightwang/FuLeTA/blob/master/Blocks.pm#L584), what do '1', '0', 'o', 'i' stand for? Can you give a clear instruction of it? Thanks.

**Comment by sunlightwang** [comment]
Hello, here the codes 1 and i for exons, and 0 and o for introns. The numbers are for one isoform (e.g. the reference isoform) and the letters for the other isoform (e.g. the query isoform).

**Comment by CrazyHsu** [comment]
@sunlightwang Thank you! I got it. BTW, I can't find download link of your pacbio data, is it still unreleased?

**Comment by sunlightwang** [comment]
If you are interested in looking at the raw data, I can provide a file transfer for you.

**Comment by CrazyHsu** [comment]
Sorry for not replying to you in time. I want test your data, can you provide it for me?

**Comment by sunlightwang** [comment]
The data can be accessed here: https://figshare.com/s/5b18138057e27c92d50e
Please note that there are CCS reads and Subreads (SUB) in the data set. Due to high error rate, we recommend correcting the subreads using, for example, https://github.com/arthuryxt/IPEC, before downstream analysis.
